language: "node_js"
node_js:
  - "6"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - "gcc-4.7"
      - "g++-4.7"
install:
  - "npm install"
script:
  - "npm test"
after_success: "npm run coveralls"